sudo: required
dist: trusty

language: node_js

node_js:
  - "5.12"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change
